services:
  - type: web
    name: tsa-moderasyon-botu
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: TOKEN
        sync: false
      - key: ROBLOX_API_KEY
        sync: false
      - key: ROBLOX_GRUP_ID
        sync: false
      - key: OWNERS
        sync: false
